version: '3.8'

services:
  app:
    build: .
    container_name: you-app-be-test
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file:
      - .env
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      MONGO_HOST: "${MONGO_HOST}"
      MONGO_PORT: "${MONGO_PORT}"
      MONGO_DB: "${MONGO_DB}"
      APP_PORT: "${APP_PORT}"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: nestjs_mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
